fixtures:
  repositories:
    apt:
      repo: git://github.com/puppetlabs/puppetlabs-apt.git
      ref: 6.1.1
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 5.1.0
    yumrepo_core:
      repo: git://github.com/puppetlabs/puppetlabs-yumrepo_core
      ref: 1.0.1
      puppet_version: ">= 6.0.0"
  symlinks:
    sensu: "#{source_dir}"
