fixtures:
  repositories:
    apt:
      repo: git://github.com/puppetlabs/puppetlabs-apt.git
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
    yumrepo_core:
      repo: git://github.com/puppetlabs/puppetlabs-yumrepo_core
      puppet_version: ">= 6.0.0"
    archive:
      repo: git://github.com/voxpupuli/puppet-archive.git
  symlinks:
    sensu: "#{source_dir}"
