fixtures:
  repositories:
    apt:
      repo: git://github.com/puppetlabs/puppetlabs-apt.git
      ref: 4.1.0
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.25.1
  symlinks:
    sensu: "#{source_dir}"
