fixtures:
  repositories:
    apt:
      repo: git://github.com/puppetlabs/puppetlabs-apt.git
      ref: 5.0.1
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.25.1
    yumrepo_core:
      repo: git://github.com/puppetlabs/puppetlabs-yumrepo_core
      ref: 1.0.1
      puppet_version: ">= 6.0.0"
    trusted_ca:
      repo: git://github.com/voxpupuli/puppet-trusted_ca.git
      ref: v2.0.0
  symlinks:
    sensu: "#{source_dir}"
